# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'decipher.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_decipher_MainWindow(object):
    def setupUi(self, decipher_MainWindow):
        decipher_MainWindow.setObjectName("decipher_MainWindow")
        decipher_MainWindow.resize(200, 100)
        decipher_MainWindow.setMinimumSize(QtCore.QSize(200, 100))
        decipher_MainWindow.setMaximumSize(QtCore.QSize(200, 100))
        self.centralwidget = QtWidgets.QWidget(decipher_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 181, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.decipher_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.decipher_pushButton.setObjectName("decipher_pushButton")
        self.verticalLayout.addWidget(self.decipher_pushButton)
        self.openfile_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.openfile_pushButton.setObjectName("openfile_pushButton")
        self.verticalLayout.addWidget(self.openfile_pushButton)
        decipher_MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(decipher_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(decipher_MainWindow)

    def retranslateUi(self, decipher_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        decipher_MainWindow.setWindowTitle(_translate("decipher_MainWindow", "Дешифратор"))
        self.decipher_pushButton.setText(_translate("decipher_MainWindow", "Дешифровать"))
        self.openfile_pushButton.setText(_translate("decipher_MainWindow", "Выбрать файл"))
