# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DecipherWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DecipherWidget(object):
    def setupUi(self, DecipherWidget):
        DecipherWidget.setObjectName("DecipherWidget")
        DecipherWidget.resize(400, 300)
        DecipherWidget.setMaximumSize(QtCore.QSize(400, 300))
        self.verticalLayoutWidget = QtWidgets.QWidget(DecipherWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 381, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info_textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.info_textEdit.setMaximumSize(QtCore.QSize(400, 110))
        self.info_textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.info_textEdit.setObjectName("info_textEdit")
        self.verticalLayout_2.addWidget(self.info_textEdit)
        self.sensitivitygroupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.sensitivitygroupBox.setObjectName("sensitivitygroupBox")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.sensitivitygroupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 336, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gyrosense_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.gyrosense_comboBox.setObjectName("gyrosense_comboBox")
        self.gyrosense_comboBox.addItem("")
        self.gyrosense_comboBox.addItem("")
        self.gyrosense_comboBox.addItem("")
        self.gyrosense_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.gyrosense_comboBox)
        self.accelsense_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.accelsense_comboBox.setCurrentText("")
        self.accelsense_comboBox.setObjectName("accelsense_comboBox")
        self.accelsense_comboBox.addItem("")
        self.accelsense_comboBox.addItem("")
        self.accelsense_comboBox.addItem("")
        self.accelsense_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.accelsense_comboBox)
        self.verticalLayout_2.addWidget(self.sensitivitygroupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openfile_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.openfile_pushButton.setObjectName("openfile_pushButton")
        self.horizontalLayout.addWidget(self.openfile_pushButton)
        self.decipher_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.decipher_pushButton.setObjectName("decipher_pushButton")
        self.horizontalLayout.addWidget(self.decipher_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.saveformat_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.saveformat_comboBox.setObjectName("saveformat_comboBox")
        self.saveformat_comboBox.addItem("")
        self.saveformat_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.saveformat_comboBox)

        self.retranslateUi(DecipherWidget)
        QtCore.QMetaObject.connectSlotsByName(DecipherWidget)

    def retranslateUi(self, DecipherWidget):
        _translate = QtCore.QCoreApplication.translate
        DecipherWidget.setWindowTitle(_translate("DecipherWidget", "Дешифратор"))
        self.sensitivitygroupBox.setTitle(_translate("DecipherWidget", "Чувствительность датчиков"))
        self.gyrosense_comboBox.setPlaceholderText(_translate("DecipherWidget", "Гироскоп"))
        self.gyrosense_comboBox.setItemText(0, _translate("DecipherWidget", "250 deg/s"))
        self.gyrosense_comboBox.setItemText(1, _translate("DecipherWidget", "500 deg/s"))
        self.gyrosense_comboBox.setItemText(2, _translate("DecipherWidget", "1000 deg/s"))
        self.gyrosense_comboBox.setItemText(3, _translate("DecipherWidget", "2000 deg/s"))
        self.accelsense_comboBox.setPlaceholderText(_translate("DecipherWidget", "Акселерометр"))
        self.accelsense_comboBox.setItemText(0, _translate("DecipherWidget", "2g"))
        self.accelsense_comboBox.setItemText(1, _translate("DecipherWidget", "4g"))
        self.accelsense_comboBox.setItemText(2, _translate("DecipherWidget", "8g"))
        self.accelsense_comboBox.setItemText(3, _translate("DecipherWidget", "16g"))
        self.openfile_pushButton.setText(_translate("DecipherWidget", "Выбрать файл"))
        self.decipher_pushButton.setText(_translate("DecipherWidget", "Дешифровать"))
        self.saveformat_comboBox.setPlaceholderText(_translate("DecipherWidget", "Формат сохранения"))
        self.saveformat_comboBox.setItemText(0, _translate("DecipherWidget", "csv"))
        self.saveformat_comboBox.setItemText(1, _translate("DecipherWidget", "hdf"))
