# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'magCalWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MagCalibrationWidget(object):
    def setupUi(self, MagCalibrationWidget):
        MagCalibrationWidget.setObjectName("MagCalibrationWidget")
        MagCalibrationWidget.resize(400, 200)
        self.magCal_textEdit = QtWidgets.QTextEdit(MagCalibrationWidget)
        self.magCal_textEdit.setGeometry(QtCore.QRect(13, 0, 381, 141))
        self.magCal_textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.magCal_textEdit.setObjectName("magCal_textEdit")
        self.magCal_pushButton = QtWidgets.QPushButton(MagCalibrationWidget)
        self.magCal_pushButton.setGeometry(QtCore.QRect(10, 150, 381, 36))
        self.magCal_pushButton.setObjectName("magCal_pushButton")

        self.retranslateUi(MagCalibrationWidget)
        QtCore.QMetaObject.connectSlotsByName(MagCalibrationWidget)

    def retranslateUi(self, MagCalibrationWidget):
        _translate = QtCore.QCoreApplication.translate
        MagCalibrationWidget.setWindowTitle(_translate("MagCalibrationWidget", "Form"))
        self.magCal_textEdit.setHtml(_translate("MagCalibrationWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Перед калибровкой подключите датчик на главном окне</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Поддерживаются только MPU9150</p></body></html>"))
        self.magCal_pushButton.setText(_translate("MagCalibrationWidget", "Калибровка магнетометра"))
